project_id = "knblffjeqnlqcdnxgmyy"

[functions.elevenlabs-tts]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.get-signed-demo-video]
verify_jwt = false

[functions.send-support-email]
verify_jwt = true
