import { useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { KNOWN_PROCESSORS, LEGAL_METADATA, USER_DIRECTED_RECIPIENTS } from "@/content/legalContent";

const PrivacyPolicy = () => {
  useEffect(() => window.scrollTo(0, 0), []);
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b"><div className="container mx-auto px-4 py-4"><Button asChild variant="ghost"><Link to="/"><ArrowLeft className="w-4 h-4" aria-hidden="true" /> Back to Home</Link></Button></div></header>
      <main className="container mx-auto px-4 py-12 max-w-4xl"><article className="prose prose-slate dark:prose-invert max-w-none">
        <h1>Privacy Policy</h1>
        <div className="border border-amber-500/40 bg-amber-500/10 rounded-lg p-4" role="status"><strong>Engineering draft — human legal approval required.</strong> This text describes repository behavior and is not a legal conclusion or an effective policy.</div>
        <p className="text-muted-foreground"><strong>Status:</strong> {LEGAL_METADATA.status}<br /><strong>Draft prepared:</strong> {LEGAL_METADATA.prepared}<br /><strong>Version:</strong> {LEGAL_METADATA.version}</p>
        <h2>1. Who operates SaveMe</h2><p>SaveMe Voice Keeper is operated by Omoha Solutions. Privacy questions and data-rights requests may be sent to <a href="mailto:victor@omohasolutions.com">victor@omohasolutions.com</a>.</p>
        <h2>2. Data SaveMe processes</h2><ul>
          <li><strong>Account and billing:</strong> name, email, authentication records, profile and preference data, and Stripe customer/subscription identifiers. Password authentication is handled by Firebase; SaveMe does not receive full card numbers.</li>
          <li><strong>Content:</strong> entries, documents, images, categories, URLs, search queries, transcripts, conversations, reminders, support requests, and content sent through user-configured integrations.</li>
          <li><strong>Derived memory and intelligence:</strong> summaries, entities, links, action items, patterns, insights, and memory/profile facts that may include health, financial, contact, work, or schedule information when a user supplies it.</li>
          <li><strong>Technical and usage data:</strong> authentication and device/request data, analytics events, pageviews, error and service logs, webhook event records, and storage/usage metadata.</li>
          <li><strong>Credentials:</strong> hashed SaveMe agent keys and, if supplied, an ElevenLabs API key stored in user preferences. Agent-key hashing does not describe storage of the optional ElevenLabs key.</li>
          <li><strong>Device storage:</strong> entries and pending changes may be cached in IndexedDB for offline sync; preferences, session pointers, and integration configuration may be held in browser storage. The browser extension may hold a short-lived Firebase token locally.</li>
        </ul>
        <h2>3. Voice and AI processing</h2><p>When the microphone is used, audio is sent over an encrypted connection through SaveMe's Google Cloud backend to Google Gemini for transcription and agent processing. The implemented server flow does not write raw microphone audio to Firestore or Cloud Storage. Transcript text and conversation turns may be stored. Provider-side handling depends on the applicable Google service configuration and contract and requires operational verification.</p>
        <p>SaveMe also sends relevant text and context to AI services to organize entries, extract memories, produce summaries and insights, and respond as Nova/Anam. This may include stored content, conversation history, profile memories, and derived context. OpenAI is used by the implemented brain-dump enhancement flow. Response or entry text may be sent to Google Cloud Text-to-Speech, ElevenLabs, MiniMax, or browser/OS speech services when those speech paths are selected.</p>
        <h2>4. Automatic memory and connected agents</h2><p>Nova may extract facts from conversations and store them in SaveMe memory. Current implementation can mirror those facts into shared memory. An agent key with read permission can read shared-memory records; write permission lets the connected agent add or change them. Visibility labels are not a substitute for a per-agent access boundary in the current implementation. Connect only agents you trust and do not give a key more permission than needed.</p>
        <p>Agent revocation and deletion workflows are being hardened. The current settings client may not successfully revoke every key, so the product must not promise immediate self-service revocation until that path is verified.</p>
        <h2>5. Purposes</h2><p>SaveMe uses data to authenticate users, provide storage and search, process voice and AI requests, organize and retrieve content, run user-requested integrations, administer subscriptions, provide support, secure and debug the service, and understand product usage. Any legal-basis, sensitive-data, international-transfer, or statutory-rights conclusion remains for counsel.</p>
        <h2>6. Processors and recipients</h2><p>The known source-evidenced processors are:</p><ul>{KNOWN_PROCESSORS.map((processor) => <li key={processor.name}><strong>{processor.name}:</strong> {processor.role}</li>)}</ul><p>Data can also go to user-directed recipients:</p><ul>{USER_DIRECTED_RECIPIENTS.map((recipient) => <li key={recipient}>{recipient}</li>)}</ul><p>SaveMe may also disclose information where required by law. Public claims about sale, sharing, targeted advertising, model training, DPAs, or transfer safeguards require counsel and contract verification and are intentionally not stated as absolute promises here.</p>
        <h2>7. Retention, export, deletion, and cancellation</h2><p>Current application records generally have no implemented automatic TTL and may remain until changed or deleted. Cloud logs, analytics, and processor-held data follow configured or provider retention that must be verified operationally. Raw microphone audio is not intentionally persisted by the implemented SaveMe server flow.</p>
        <p>The current in-product export is a limited JSON download containing entries, shared memories, preferences, and agent-key metadata; it is not a complete portable archive and does not include raw keys. The approved data-rights foundation calls for a server-generated archive with versioned JSON, original files, checksums, schema metadata, and an index, expiring after seven days, but that production workflow is not yet implemented.</p>
        <p>Subscription cancellation stops renewal but does not delete the account or its data. Current account deletion requires contacting support and does not yet run the approved manifest-driven purge. The approved target requires recent authentication, immediate revocation of agent and scheduled access, asynchronous deletion of user content, derived records, mirrors, storage objects, and applicable local data, with Firebase Auth deleted last. The target maximum is 30 days after a valid request, subject only to documented, minimized legal, billing, fraud, security, or deletion-receipt exceptions. Do not rely on that target as a description of the current unimplemented workflow.</p>
        <h2>8. Security and choices</h2><p>Traffic uses HTTPS/TLS and Google Cloud/Firebase provide infrastructure encryption at rest. Access controls are implemented for many user-owned records, but no system is completely secure. Multi-factor authentication is not currently implemented.</p><p>Users can edit many account settings and records, download the limited export described above, disconnect user-configured webhook destinations, and request privacy assistance by email. Analytics consent/opt-out and comprehensive self-service rights workflows are not currently implemented.</p>
        <h2>9. Legal review questions</h2><p>Counsel must approve the effective date and version, controller identity/contact details, jurisdiction and age terms, legal bases, statutory notices and request timelines, sensitive-data treatment, sale/share/advertising characterizations, processor contracts and training/retention terms, international-transfer language, and retention exceptions before release.</p>
        <nav aria-label="Legal documents" className="mt-10 flex gap-4"><Link to="/terms">Terms of Service</Link><a href="mailto:victor@omohasolutions.com?subject=Privacy%20Inquiry%20-%20SaveMe">Privacy contact</a></nav>
      </article></main>
    </div>
  );
};
export default PrivacyPolicy;
