import { useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { LEGAL_METADATA } from "@/content/legalContent";

const TermsOfService = () => {
  useEffect(() => window.scrollTo(0, 0), []);
  return <div className="min-h-screen bg-background">
    <header className="border-b"><div className="container mx-auto px-4 py-4"><Button asChild variant="ghost"><Link to="/"><ArrowLeft className="w-4 h-4" aria-hidden="true" /> Back to Home</Link></Button></div></header>
    <main className="container mx-auto px-4 py-12 max-w-4xl"><article className="prose prose-slate dark:prose-invert max-w-none">
      <h1>Terms of Service</h1>
      <div className="border border-amber-500/40 bg-amber-500/10 rounded-lg p-4" role="status"><strong>Engineering draft — human legal approval required.</strong> These operational terms are not effective until approved by qualified counsel and the product owner.</div>
      <p className="text-muted-foreground"><strong>Status:</strong> {LEGAL_METADATA.status}<br /><strong>Draft prepared:</strong> {LEGAL_METADATA.prepared}<br /><strong>Version:</strong> {LEGAL_METADATA.version}</p>
      <h2>1. Service</h2><p>SaveMe Voice Keeper is a cloud service operated by Omoha Solutions for capturing, storing, organizing, searching, and exporting user content through text, uploaded files, voice input, AI processing, and optional agent or webhook connections. Features can be changed, interrupted, or unavailable, and AI output and transcription may contain errors.</p>
      <h2>2. Accounts and acceptable use</h2><p>Users must provide accurate account information, protect their credentials and agent keys, and use the service lawfully. Users must not attempt unauthorized access, disrupt the service, upload malicious code, or use SaveMe to violate another person's rights. Age eligibility, parental-consent language, governing law, dispute terms, warranty exclusions, and liability terms require counsel approval and are not concluded by this engineering draft.</p>
      <h2>3. Voice, AI, and memory</h2><p>Voice audio is transmitted to Google Gemini through Google Cloud for transcription and agent processing; the implemented SaveMe server does not persist raw microphone audio in Firestore or Cloud Storage. Transcript and conversation text can be stored. Relevant content and memory context can be processed by Google and, in specific implemented paths, OpenAI. Text-to-speech may use Google, ElevenLabs, MiniMax, or browser/OS speech services. See the <Link to="/privacy">Privacy Policy engineering draft</Link> for details and known operational limits.</p>
      <p>Nova may automatically extract and store facts from conversations, including sensitive facts a user chooses to provide, and can mirror them to shared memory. Users are responsible for reviewing AI-created content and deciding what to provide.</p>
      <h2>4. Connected agents and integrations</h2><p>A user who creates and supplies an agent key directs SaveMe to let that third-party agent access shared memory according to the key's read/write permissions. A read key can expose the shared-memory corpus; a write key can change it. Current visibility labels do not provide a verified per-agent record boundary. Users should connect only trusted agents, protect raw keys, and use the least permission needed. Self-service revocation is not yet implemented as a verified reliable path and must not be relied on as instantaneous.</p><p>User-configured webhooks and Zapier destinations can receive full entry objects and account email. The user is responsible for the destination and its terms.</p>
      <h2>5. Plans, billing, cancellation, and refunds</h2><p>The approved launch catalog is Free ($0, 50 entries, 500 MB), Basic ($9/month, unlimited entries, 5 GB), and Premium ($19/month, unlimited entries, 50 GB). Plans are monthly. The Free plan is the no-card evaluation path; there is no paid trial. Stripe-hosted card checkout is the only launch payment method.</p><p>Upgrades take effect immediately with Stripe proration. Downgrades and cancellations take effect at the end of the paid period. A past-due paid subscription has a seven-day grace period. After downgrade or grace expiry, existing content remains readable and exportable while over-limit writes may be locked. Cancellation stops renewal and does not delete account data. No partial-month refunds are offered except where required by law.</p>
      <h2>6. Export and account deletion</h2><p>The current product offers a limited JSON export of entries, shared memories, preferences, and agent-key metadata. It is not a backup or a complete portable archive. The approved full archive and restore-independent data-rights workflow remain under implementation.</p><p>Account deletion is separate from cancellation. Current settings direct users to support and do not implement the approved asynchronous purge. The approved target requires recent authentication, agent/scheduled-access revocation first, manifest-driven deletion of application, derived, mirrored, storage, and applicable device-side data, and Auth identity deletion last, as soon as practical and no later than 30 days after a valid request, subject to narrowly documented retention exceptions. This target is not a claim that the current workflow is operational.</p>
      <h2>7. Contact and legal gate</h2><p>Questions may be sent to <a href="mailto:victor@omohasolutions.com">victor@omohasolutions.com</a>. Counsel must approve final assent mechanics, operator/contact details, age and jurisdiction terms, intellectual-property terms, suspension rights, warranty and liability language, dispute process, statutory consumer terms, notice procedures, and effective/version metadata before publication.</p>
      <nav aria-label="Legal documents" className="mt-10 flex gap-4"><Link to="/privacy">Privacy Policy</Link><a href="mailto:victor@omohasolutions.com?subject=Terms%20Inquiry%20-%20SaveMe">Contact</a></nav>
    </article></main>
  </div>;
};
export default TermsOfService;
