// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knblffjeqnlqcdnxgmyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYmxmZmplcW5scWNkbnhnbXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTc1MzYsImV4cCI6MjA2Njk5MzUzNn0.I24P5R0CDzwmXYbSOf3IdT_B0yd7nlZYvl3QeDeNkwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});